### ISSUE TITLE
Diffusion de la radio sur les lecteurs de smartphone

### ISSUE THREAD

**Issue by Lurikbolding** [musique-libre/radio.dogmazic.net#3]
Bonjour
Je viens de découvrir votre radio. Moment agréable pour découvrir de la musique.
Mais celle ci n'est pas disponible sur les lecteurs "webradio" des smartphones.
Par exemple : Radiodroid : https://f-droid.org/fr/packages/net.programmierecke.radiodroid2/

Serait il possible d'ajouter votre flux dans la liste des radios disponible? 
J'ai trouvé radio-browser ici : https://www.radio-browser.info/
qui liste les url des flux (c'est un wiki, donc modifiable).
Cela permettrait d'écouter votre flux facilement depuis un smartphone.

**Comment by shangril** [comment]
Bonjour, 

Actuellement l'association Musique Libre qui édite Dogmazic, et contrairement à ce qui a pu être le cas par le passé, ne comporte aucun bénévole pour se charger de faire lister notre radio dans les annuaires requiérant une inscription manuelle. C'est possiblement appelé peut-être à changer selon les motivations et les équipes qui se forment. En attendant notre flux, suite à votre Issue, a été configuré pour automatiquement être listé, via le logiciel de diffusion, avec mise à jour du titre en rotation et des éventuels changements (descriptions, styles et autre), dans l'annuaire officiel du projet Icecast, dir.xiph.org , dans lequel de nombreux logiciels clients vont chercher leur liste de flux. 

S., secrétaire adjoint de Musique Libre
